# Site settings
title: Github Blog
email: chaucerling@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  何でもは知らないわよ、知ってることだけ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  chaucerling

# Build settings
# markdown: kramdown
# kramdown:
#   input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks]
